//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::api_access_token::Entity as ApiAccessToken;
pub use super::device::Entity as Device;
pub use super::otp_record::Entity as OtpRecord;
pub use super::otp_request::Entity as OtpRequest;
pub use super::user::Entity as User;
pub use super::user_device::Entity as UserDevice;
pub use super::user_limit::Entity as UserLimit;
