//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub enabled: bool,
    pub admin: bool,
    pub token_version_at: DateTimeUtc,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::otp_record::Entity")]
    OtpRecord,
    #[sea_orm(has_many = "super::user_device::Entity")]
    UserDevice,
    #[sea_orm(has_one = "super::user_limit::Entity")]
    UserLimit,
}

impl Related<super::otp_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OtpRecord.def()
    }
}

impl Related<super::user_device::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserDevice.def()
    }
}

impl Related<super::user_limit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLimit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
