//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "api_access_token")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub otp_record_id: Uuid,
    #[sea_orm(unique)]
    pub token_hash: String,
    pub name: String,
    pub last_used_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::otp_record::Entity",
        from = "Column::OtpRecordId",
        to = "super::otp_record::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OtpRecord,
}

impl Related<super::otp_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OtpRecord.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
